export const ALL_MODEL_REQUEST = "ALL_MODEL_REQUEST";
export const ALL_MODEL_SUCCESS = "ALL_MODEL_SUCCESS";
export const ALL_MODEL_FAIL = "ALL_MODEL_FAIL";

export const FEATURED_MODEL_FAIL = "FEATURED_MODEL_FAIL";
export const FEATURED_MODEL_REQUEST = "FEATURED_MODEL_REQUEST";
export const FEATURED_MODEL_SUCCESS = "FEATURED_MODEL_SUCCESS";

export const ADMIN_MODEL_REQUEST = "ADMIN_MODEL_REQUEST";
export const ADMIN_MODEL_SUCCESS = "ADMIN_MODEL_SUCCESS";
export const ADMIN_MODEL_FAIL = "ADMIN_MODEL_FAIL";

export const NEW_MODEL_REQUEST = "NEW_MODEL_REQUEST";
export const NEW_MODEL_SUCCESS = "NEW_MODEL_SUCCESS";
export const NEW_MODEL_RESET = "NEW_MODEL_RESET";
export const NEW_MODEL_FAIL = "NEW_MODEL_FAIL";

export const MODEL_DETAILS_REQUEST = "MODEL_DETAILS_REQUEST";
export const MODEL_DETAILS_SUCCESS = "MODEL_DETAILS_SUCCESS";
export const MODEL_DETAILS_FAIL = "MODEL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";